# Change these first
owner: dieualban # Your GitHub username
repo: uptime # Your Github repository name

# Add your sites here
sites:
  - name: Corsicaweb
    url: https://www.corsicaweb.fr
  - name: Marengo
    url: https://www.domaine-marengo.fr
  - name: Super Petit
    url: https://www.superpetit.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #  cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://www.corsicaweb.fr/wp-content/uploads/2018/10/logo-corsicaweb-new.png
  name: Corsicaweb Upptime
  introTitle: "Monitor and status page."
  introMessage: (https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
